version: "3.9"
services:
  auth-api:
    build: ./auth-api
    networks:
    - app-network
    ports:
      - "5000:5000"
  core-api:
    build: ./core-api
    networks:
    - app-network
    ports:
      - "6000:6000"
  psp-connector:
    build: ./psp-connector
    networks:
    - app-network
    ports:
      - "7000:7000"
  redis:
    image: redis
    networks:
    - app-network
    ports:
      - "6379:6379"
  nginx:
    image: nginx
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
        - app-network
    ports:
        - "80:80"

    depends_on:
        - auth-api
        - core-api
        - psp-connector
networks:
  app-network: {}